#
# This file is part of the clavem.js npm package. Copyright (C) 2016 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

language: node_js
script: npm run-script travis-ci
node_js:
  - "6"
notifications:
  email: false